/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestor.Pantallas;

import Gestor.Entidades.Especialidad;
import Gestor.Entidades.Medico;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author KELVIN VR
 */
public class JFrameAgregarMedico extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAgregarMedico
     */
    JFrameMedicos padre;
    Medico medico;
    List <Especialidad> listaespecialidad;
    public JFrameAgregarMedico(JFrameMedicos padre) {
        initComponents();
        listaespecialidad = new ArrayList<>();
        medico = new Medico();
        this.padre = padre;
    }
    private DefaultListModel modeloListMedicos;
   
    public void llenarJList() {
        modeloListMedicos = new DefaultListModel();
        lstespecialidades.setModel(modeloListMedicos);
        modeloListMedicos.removeAllElements();
        for (Especialidad especialidad : listaespecialidad) {
           
            modeloListMedicos.addElement(especialidad.getNombre());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombremedico = new javax.swing.JTextField();
        txtCMPmedico = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstespecialidades = new javax.swing.JList<>();
        btnadd = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombremedico.setBackground(new java.awt.Color(102, 255, 102));

        txtCMPmedico.setBackground(new java.awt.Color(102, 255, 102));

        btncancelar.setBackground(new java.awt.Color(255, 51, 51));
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(51, 0, 255));
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("CMP");

        jLabel1.setText("Agregar Medico");

        lstespecialidades.setBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(lstespecialidades);

        btnadd.setBackground(new java.awt.Color(0, 0, 255));
        btnadd.setText("+");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnquitar.setBackground(new java.awt.Color(255, 0, 0));
        btnquitar.setText("-");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        jLabel4.setText("Especialidades");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCMPmedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(txtNombremedico, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btncancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addComponent(btnguardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnquitar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnadd)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombremedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCMPmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd)
                    .addComponent(btnquitar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btncancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        if(!txtCMPmedico.getText().isEmpty() &&
            !txtNombremedico.getText().isEmpty()
            && !listaespecialidad.isEmpty()){
            datosMedico();
            this.dispose();
            padre.llenarJList();
            padre.setVisible(true);        
        }
        else{
              JOptionPane.showMessageDialog(null, "Completa todos los campos"
                    ,"Agregar Medico", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void datosMedico() {
        String cmp =txtCMPmedico.getText();
        String nombre = txtNombremedico.getText();
        medico.setCMP(cmp);
        medico.setNombre(nombre);
        medico.setEspecialidades(listaespecialidad);
        padre.addMedico(medico);
    }

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:        
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String especialidadnombre = "";
        especialidadnombre = JOptionPane.showInputDialog(null, "Ingrese especialidad: "
                , "Agregar especialidad",0);
        if(!"".equals(especialidadnombre)){
            Especialidad especialidad = new Especialidad();
            especialidad.setNombre(especialidadnombre);
            listaespecialidad.add(especialidad);            
            llenarJList();
            
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar una especialidad"
                    ,"Agregar especialidad", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        // TODO add your handling code here:
        int indice = lstespecialidades.getSelectedIndex();        
        if(indice!=-1){   
            listaespecialidad.remove(indice);
            llenarJList();                      
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecciones una especialidad de la lista"
                    ,"Eliminar especialidad", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnquitarActionPerformed

    /**
     * @param args the command line argumentstxtCMP   
     * */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnquitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstespecialidades;
    private javax.swing.JTextField txtCMPmedico;
    private javax.swing.JTextField txtNombremedico;
    // End of variables declaration//GEN-END:variables
}
