/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestor.Pantallas;

import Gestor.Entidades.Cita;
import Gestor.Entidades.Paciente;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KELVIN VR
 */
public class JFramePacientes extends javax.swing.JFrame {

    /**
     * Creates new form PantallPacientes
     */
      
    JFrameEditarCita padre;
    private DefaultListModel modeloListPacientes;
    static List<Paciente> listaPacientes = new ArrayList() ;
    public JFramePacientes(JFrameEditarCita padre) {
        initComponents();
        
        this.padre = padre;
        llenarJList();
    }
    public void llenarJList() {
        modeloListPacientes = new DefaultListModel();
        lstpacientes.setModel(modeloListPacientes);
        modeloListPacientes.removeAllElements();
         for (Paciente paciente : listaPacientes) {
           
            modeloListPacientes.addElement(paciente.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtbuscarpaciente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstpacientes = new javax.swing.JList<>();
        btnSalir = new javax.swing.JButton();
        btnagregarPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pacientes");

        txtbuscarpaciente.setBackground(new java.awt.Color(255, 204, 204));
        txtbuscarpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarpacienteActionPerformed(evt);
            }
        });
        txtbuscarpaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarpacienteKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lstpacientes.setBackground(new java.awt.Color(255, 204, 204));
        lstpacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstpacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstpacientes);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnagregarPaciente.setText("Crear ");
        btnagregarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnagregarPaciente))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtbuscarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtbuscarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir)
                            .addComponent(btnagregarPaciente))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void addPaciente (Paciente paciente){
        listaPacientes.add(paciente);
    }
    private void txtbuscarpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarpacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarpacienteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnagregarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarPacienteActionPerformed
        // TODO add your handling code here:
        JFrameAgregarPaciente agregarPaciente = new JFrameAgregarPaciente(this);
        agregarPaciente.setLocationRelativeTo(null);
        agregarPaciente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnagregarPacienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        modeloListPacientes.removeAllElements();
        for (Paciente paciente : listaPacientes) {
            if(paciente.getNombre().contains(txtbuscarpaciente.getText())){
                modeloListPacientes.addElement(paciente.toString());
            }
        
        }       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void lstpacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstpacientesMouseClicked
        int indice = lstpacientes.getSelectedIndex();
        if(indice!=-1 && evt.getClickCount()==2){
            this.dispose();
            Paciente paciente = listaPacientes.get(indice);
            padre.addPaciente(paciente);
            padre.setVisible(true);
            
        }
       
       
        
    }//GEN-LAST:event_lstpacientesMouseClicked

    private void txtbuscarpacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarpacienteKeyTyped
        // TODO add your handling code here:
        if(txtbuscarpaciente.getText().isEmpty())
        {
          llenarJList();
        }
    }//GEN-LAST:event_txtbuscarpacienteKeyTyped

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnagregarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstpacientes;
    private javax.swing.JTextField txtbuscarpaciente;
    // End of variables declaration//GEN-END:variables
}
