/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestor.Pantallas;

import Gestor.Entidades.Medico;
import Gestor.Entidades.Paciente;
import static Gestor.Pantallas.JFramePacientes.listaPacientes;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author KELVIN VR
 */
public class JFrameMedicos extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMedicos
     */
    JFrameEditarCita padre;
    static List<Medico> listaMedicos = new ArrayList();
    private DefaultListModel modeloListMedicos;
    public JFrameMedicos(JFrameEditarCita padre) {
        initComponents();
        this.padre = padre;
        llenarJList();
    }
    public void llenarJList() {
        modeloListMedicos = new DefaultListModel();
        lstMedicos.setModel(modeloListMedicos);
        modeloListMedicos.removeAllElements();
        for (Medico medico : listaMedicos) {           
            modeloListMedicos.addElement(medico.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtbuscarmedico = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMedicos = new javax.swing.JList<>();
        btnSalir = new javax.swing.JButton();
        btnagregarMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Medicos");

        txtbuscarmedico.setBackground(new java.awt.Color(255, 204, 204));
        txtbuscarmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarmedicoActionPerformed(evt);
            }
        });
        txtbuscarmedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarmedicoKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lstMedicos.setBackground(new java.awt.Color(255, 204, 204));
        lstMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstMedicos);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnagregarMedico.setText("Crear ");
        btnagregarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnagregarMedico))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtbuscarmedico, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(btnBuscar)))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnagregarMedico))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void addMedico(Medico medico){
        listaMedicos.add(medico);
    }
    
    private void txtbuscarmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarmedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarmedicoActionPerformed

    private void btnagregarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarMedicoActionPerformed
        JFrameAgregarMedico agregarMedico = new JFrameAgregarMedico(this);
        agregarMedico.setLocationRelativeTo(null);
        agregarMedico.setVisible(true);        
        this.setVisible(false);
    }//GEN-LAST:event_btnagregarMedicoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lstMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMedicosMouseClicked
        int indice = lstMedicos.getSelectedIndex();
        if(indice!=-1 && evt.getClickCount()==2){
            this.dispose();
            Medico medico = listaMedicos.get(indice);
            padre.addMedico(medico);
            padre.addFechaHora();
            padre.setVisible(true);
            
            
        }
    }//GEN-LAST:event_lstMedicosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        modeloListMedicos.removeAllElements();
        for (Medico medico : listaMedicos) {
            if(medico.getNombre().contains(txtbuscarmedico.getText())){
                modeloListMedicos.addElement(medico.toString());
            }
        
        } 
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtbuscarmedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarmedicoKeyTyped
     
        if(txtbuscarmedico.getText().isEmpty())
        {
          llenarJList();
        }
    }//GEN-LAST:event_txtbuscarmedicoKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnagregarMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstMedicos;
    private javax.swing.JTextField txtbuscarmedico;
    // End of variables declaration//GEN-END:variables
}
