package Gestor.Pantallas;

import Gestor.Entidades.Cita;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KELVIN VR
 */
public class JFrameGestorCitas extends javax.swing.JFrame {
    private static List<Cita> listaCitas = new ArrayList<Cita>();
    private DefaultListModel modeloListCitas;
    /**
     * Creates new form PantallaGestorCitas
     */
    public JFrameGestorCitas() {
        initComponents();
        llenarJList();
        
    }

    private void llenarJList() {
        modeloListCitas = new DefaultListModel();
        JListCitas.setModel(modeloListCitas);
        modeloListCitas.removeAllElements();
         for (Cita cita : listaCitas) {
           
            modeloListCitas.addElement(cita.toString());
        }
    }
    public void addCita(Cita cita){
        listaCitas.add(cita);
        llenarJList();                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCrearCita = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListCitas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar Cita");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCrearCita.setText("Crear Cita");
        btnCrearCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCitaActionPerformed(evt);
            }
        });

        txtBuscar.setBackground(new java.awt.Color(255, 204, 204));

        JListCitas.setBackground(new java.awt.Color(255, 204, 204));
        JListCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JListCitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JListCitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(btnCrearCita))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtBuscar))
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnCrearCita))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        modeloListCitas.removeAllElements();
        for (Cita cita : listaCitas) {
            cita.getPaciente().getNombre().contains(txtBuscar.getText());
            modeloListCitas.addElement(cita.toString());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCrearCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCitaActionPerformed
        // TODO add your handling code here:
        JFrameEditarCita nuevaCita = new JFrameEditarCita(this);
        nuevaCita.setLocationRelativeTo(null);
        nuevaCita.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearCitaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
       int indice = JListCitas.getSelectedIndex();
        if(indice!=-1){
            listaCitas.remove(indice);
            llenarJList();
            JOptionPane.showMessageDialog(null, "Cita eliminada "
                    ,"Eliminar Cita", JOptionPane.INFORMATION_MESSAGE);
        }else{
             JOptionPane.showMessageDialog(null, "Selecciona un cita de la lista"
                    ,"Eliminar Cita", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void JListCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListCitasMouseClicked
        // TODO add your handling code here:
        int indice = JListCitas.getSelectedIndex();
        if( indice!=-1 && evt.getClickCount() == 2){
            Cita cita = listaCitas.get(indice);
            JFrameEditarCita visualizarCita = new JFrameEditarCita(cita,this);
            visualizarCita.modificarFrame();
            visualizarCita.setLocationRelativeTo(null);
            visualizarCita.setSize(290,355);
            visualizarCita.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_JListCitasMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListCitas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearCita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
